[package]
name = "moneymarket"
version = "0.3.1"
authors = ["Terraform Labs, PTE."]
edition = "2018"
description = "Common helpers for other moneymarket specs"
license = "Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = "0.12.1"
cosmwasm-bignumber = {path = "../bignumber", version = "2.3.0"}
terra-cosmwasm ={path = "../terra-cosmwasm", version = "2.3.0"}
cosmwasm-storage = "1.0.0"
cosmwasm-std = "1.0.0"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = "1.0.0"

[profile.dev]
overflow-checks = true

[profile.release]
overflow-checks = true