[package]
name = "moneymarket"
version = "0.3.1"
authors = ["Terraform Labs, PTE."]
edition = "2018"
description = "Common helpers for other moneymarket specs"
license = "Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = "0.5.0"
cosmwasm-bignumber = {path = "../bignumber", version = "2.3.0"}
oraiswap = {path = "../oraiswap", version = "2.4.1"}
cosmwasm-storage = { version = "0.13.2", features = ["iterator"] }
cosmwasm-std = "0.13.2"
schemars = "0.7"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = "0.13.2"

[profile.dev]
overflow-checks = true

[profile.release]
overflow-checks = true